---
namespace: znerol
name: become_password
version: 1.0.1
readme: README.md
authors:
  - Lorenz Schori
description: |
    Provides an ansible vars plugin which looks up become password using a user
    specified command.
license:
  - GPL-3.0-or-later
tags:
  - become
  - password
  - security
  - sudo
  - utilities
dependencies: {}
build_ignore:
  - .github
repository: https://github.com/znerol/ansible-collection-become-password.git
documentation: https://github.com/znerol/ansible-collection-become-password
homepage: https://github.com/znerol/ansible-collection-become-password
issues: https://github.com/znerol/ansible-collection-become-password/issues
